export const AIEventTypes = {
  AI_MESSAGE_SENT: "AI_MESSAGE_SENT",
  AI_RESPONSE_RECEIVED: "AI_RESPONSE_RECEIVED",

  AI_TOOL_REQUESTED: "AI_TOOL_REQUESTED",
  AI_TOOL_EXECUTED: "AI_TOOL_EXECUTED",

  AI_CONTEXT_UPDATED: "AI_CONTEXT_UPDATED",

  AI_STREAM_STARTED: "AI_STREAM_STARTED",
  AI_STREAM_CHUNK: "AI_STREAM_CHUNK",
  AI_STREAM_FINISHED: "AI_STREAM_FINISHED",
};
